<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything (pipe)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT pipe EMPTY>
	<!ATTLIST pipe id NMTOKEN #REQUIRED>
	<!ATTLIST pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST pipe expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="untitled.xml"
		unuid="1473088232794.1641762737.958893250"
		mipmaps_folder="trakem2.1473088232794.1641762737.958893250/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
	>
		<anything id="460" expanded="true">
			<pipe id="462" oid="461"/>
			<pipe id="464" oid="463"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="438.0"
		layer_height="404.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_pipe
			oid="461"
			width="130.0"
			height="204.0"
			transform="matrix(1.0,0.0,0.0,1.0,120.0,106.0)"
			title="pipe"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
			d="M 3.0,10.0 C 3.0,10.0 60.0,28.0 60.0,28.0 C 60.0,28.0 103.0,94.0 103.0,94.0 C 103.0,94.0 119.0,203.0 119.0,203.0"
			layer_ids="300,273,222,168"
			p_width="11.342202246984467,11.342202246984467,11.342202246984467,11.342202246984467"
		>
		</t2_pipe>
		<t2_pipe
			oid="463"
			width="351.0"
			height="249.0"
			transform="matrix(1.0,0.0,0.0,1.0,69.0,138.9999999999999)"
			title="pipe"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;stroke-opacity:1.0"
			d="M 11.0,3.000000000000057 C 11.0,3.000000000000057 31.0,116.0 115.0,70.00000000000006 C 197.0,24.000000000000107 195.0,104.0 219.0,177.0 C 243.0,249.0 276.0,206.0 284.0,203.0 C 290.0,200.0 325.0,160.0 298.0,192.0 C 271.0,225.0 259.0,58.0 305.0,137.0"
			layer_ids="225,225,207,204,189,189"
			p_width="11.342202246984467,11.342202246984467,11.342202246984467,11.342202246984467,11.342202246984467,11.342202246984467"
		>
		</t2_pipe>
		<t2_layer oid="5"
			 thickness="1.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="8"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:150 RGB_kept_stack 1"
				links="11"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=1"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="1.0"
			 z="1.0"
			 title=""
		>
			<t2_patch
				oid="11"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:151 RGB_kept_stack 2"
				links="8,14"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=2"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="1.0"
			 z="2.0"
			 title=""
		>
			<t2_patch
				oid="14"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:152 RGB_kept_stack 3"
				links="11,17"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=3"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="1.0"
			 z="3.0"
			 title=""
		>
			<t2_patch
				oid="17"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:153 RGB_kept_stack 4"
				links="14,20"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=4"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="1.0"
			 z="4.0"
			 title=""
		>
			<t2_patch
				oid="20"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:154 RGB_kept_stack 5"
				links="17,23"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=5"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="1.0"
			 z="5.0"
			 title=""
		>
			<t2_patch
				oid="23"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:155 RGB_kept_stack 6"
				links="20,26"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=6"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="1.0"
			 z="6.0"
			 title=""
		>
			<t2_patch
				oid="26"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:156 RGB_kept_stack 7"
				links="23,29"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=7"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="1.0"
			 z="7.0"
			 title=""
		>
			<t2_patch
				oid="29"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:157 RGB_kept_stack 8"
				links="26,32"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=8"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="30"
			 thickness="1.0"
			 z="8.0"
			 title=""
		>
			<t2_patch
				oid="32"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:158 RGB_kept_stack 9"
				links="29,35"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=9"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="33"
			 thickness="1.0"
			 z="9.0"
			 title=""
		>
			<t2_patch
				oid="35"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:159 RGB_kept_stack 10"
				links="32,38"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=10"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="36"
			 thickness="1.0"
			 z="10.0"
			 title=""
		>
			<t2_patch
				oid="38"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:160 RGB_kept_stack 11"
				links="35,41"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=11"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="39"
			 thickness="1.0"
			 z="11.0"
			 title=""
		>
			<t2_patch
				oid="41"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:161 RGB_kept_stack 12"
				links="38,44"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=12"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="42"
			 thickness="1.0"
			 z="12.0"
			 title=""
		>
			<t2_patch
				oid="44"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:162 RGB_kept_stack 13"
				links="41,47"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=13"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="45"
			 thickness="1.0"
			 z="13.0"
			 title=""
		>
			<t2_patch
				oid="47"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:163 RGB_kept_stack 14"
				links="44,50"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=14"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="48"
			 thickness="1.0"
			 z="14.0"
			 title=""
		>
			<t2_patch
				oid="50"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:164 RGB_kept_stack 15"
				links="47,53"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=15"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="51"
			 thickness="1.0"
			 z="15.0"
			 title=""
		>
			<t2_patch
				oid="53"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:165 RGB_kept_stack 16"
				links="50,56"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=16"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="54"
			 thickness="1.0"
			 z="16.0"
			 title=""
		>
			<t2_patch
				oid="56"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:166 RGB_kept_stack 17"
				links="53,59"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=17"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="57"
			 thickness="1.0"
			 z="17.0"
			 title=""
		>
			<t2_patch
				oid="59"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:167 RGB_kept_stack 18"
				links="56,62"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=18"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="60"
			 thickness="1.0"
			 z="18.0"
			 title=""
		>
			<t2_patch
				oid="62"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:168 RGB_kept_stack 19"
				links="59,65"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=19"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="63"
			 thickness="1.0"
			 z="19.0"
			 title=""
		>
			<t2_patch
				oid="65"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:169 RGB_kept_stack 20"
				links="62,68"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=20"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="66"
			 thickness="1.0"
			 z="20.0"
			 title=""
		>
			<t2_patch
				oid="68"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:170 RGB_kept_stack 21"
				links="65,71"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=21"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="69"
			 thickness="1.0"
			 z="21.0"
			 title=""
		>
			<t2_patch
				oid="71"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:171 RGB_kept_stack 22"
				links="68,74"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=22"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="72"
			 thickness="1.0"
			 z="22.0"
			 title=""
		>
			<t2_patch
				oid="74"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:172 RGB_kept_stack 23"
				links="71,77"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=23"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="75"
			 thickness="1.0"
			 z="23.0"
			 title=""
		>
			<t2_patch
				oid="77"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:173 RGB_kept_stack 24"
				links="74,80"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=24"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="78"
			 thickness="1.0"
			 z="24.0"
			 title=""
		>
			<t2_patch
				oid="80"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:174 RGB_kept_stack 25"
				links="77,83"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=25"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="81"
			 thickness="1.0"
			 z="25.0"
			 title=""
		>
			<t2_patch
				oid="83"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:175 RGB_kept_stack 26"
				links="80,86"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=26"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="84"
			 thickness="1.0"
			 z="26.0"
			 title=""
		>
			<t2_patch
				oid="86"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:176 RGB_kept_stack 27"
				links="83,89"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=27"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="87"
			 thickness="1.0"
			 z="27.0"
			 title=""
		>
			<t2_patch
				oid="89"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:177 RGB_kept_stack 28"
				links="86,92"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=28"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="90"
			 thickness="1.0"
			 z="28.0"
			 title=""
		>
			<t2_patch
				oid="92"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:178 RGB_kept_stack 29"
				links="89,95"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=29"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="93"
			 thickness="1.0"
			 z="29.0"
			 title=""
		>
			<t2_patch
				oid="95"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:179 RGB_kept_stack 30"
				links="92,98"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=30"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="96"
			 thickness="1.0"
			 z="30.0"
			 title=""
		>
			<t2_patch
				oid="98"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:180 RGB_kept_stack 31"
				links="95,101"
				type="4"
				file_path="/home/fewtrem/RGB kept stack.tif-----#slice=31"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="438"
				o_height="404"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="99"
			 thickness="1.0"
			 z="31.0"
			 title=""
		>
			<t2_patch
				oid="101"
				width="438.0"
				height="404.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="slice:181 RGB_kept_stack 32"